
# Adapted from https://gist.github.com/ThabetAmer/b818a262c71467c7403fd75bc526b8f9

# version: "3.7"

services:

  sonarqube:
    container_name: sonarqube
    image: sonarqube:7.9.2-community
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=2c71d75bc526467c7403fb818a26b8f9
      - SONAR_TOKEN=iouscretghv9w7y4ojxthow39
      - SONARQUBE_USERNAME=admin
      - SONAR_LOGIN=admin
      - SONAR_PASSWORD=2c71d75bcs4hq934tdjqngtsojxercm
      - SONAR_WEB_PORT=9000
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - sonarnet
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    container_name: sonardb
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=2c71d75bc526467c7403fb818a26b8f9
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
