# See README.md for instructions to run stages

# Data already imported via:
# dvc import --out ./data/SKAB https://github.com/waico/SKAB.git ./data
# To update, run:
# dvc update data/SKAB

stages:
  # ANOMALY DETECTION (AD) STAGES
  run_anomaly_detection:
    desc: "Run anomaly detection experiments on SKAB datasets"
    cmd: python -m ml.ad
    deps:
      - data/SKAB
    outs:
      - results/ad/all_metadata.json

  # SOURCE CODE ANALYSIS (SCA) STAGES
  prepare_repositories:
    desc: "Prepare repositories for source code analysis"
    cmd: python src/ml/sca/repo.py
    deps:
      - src/ml/__init__.py
      - src/ml/sca/repo.py
    outs:
      - results/sca/git_analysis/1_ALL_LIBRARIES.csv

  run_source_code_analysis:
    desc: "Run source code analysis on the project"
    cmd: |
      python -m ml.sca repositories results
    deps:
      - src/ml/__init__.py
      - src/ml/sca/__init__.py
      - src/ml/sca/__main__.py
      - src/ml/sca/analysis.py
      - src/ml/sca/repo.py
      - src/ml/sca/reporting.py
      - results/sca/git_analysis/1_ALL_LIBRARIES.csv
    outs:
      - results/sca/SUMMARY/T_summary.csv
